# -*- coding: utf-8 -*-
"""PalmerPenguinsM3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IWgqyerRlb-EeKelQch1c0BZ0GB4GDu_
"""

#PalmerPenguinsM3.py
#Alexandria Herbert
#10-5-26
#Calculates and displays Palmer Penguin statistics.

import math

#constants
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

#list of species names
species_names = [
    SP_CHINSTRAP,
    SP_GENTOO,
    SP_ADELIE
]

#list of species counts
species_counts = [
    NUM_CHINSTRAP,
    NUM_GENTOO,
    NUM_ADELIE
]

#calculate dataset stats
total_species = len(species_names)
total_penguins = sum(species_counts)
average_penguins = total_penguins / total_species
average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percent = species_counts[1] / total_penguins * 100
adelie_percent = species_counts[2] / total_penguins * 100

largest_count = max(species_counts)
smallest_count = min(species_counts)

largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)

largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]


#Output the species names with introductory text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!" )
print()

print(f"There are a total of {total_species} penguin species in this dataset.")
print(f"There are a total of {total_penguins} penguins in this dataset.")
print(f"The average number of penguins per species is {average_penguins}.")
print(f"The average rounded up is {average_penguins_rounded_up} penguins.")

print()

print(f"{SP_CHINSTRAP}: {species_counts[0]} ({chinstrap_percent}%)")
print(f"{SP_GENTOO}: {species_counts[1]} ({gentoo_percent}%)")
print(f"{SP_ADELIE}: {species_counts[2]} ({adelie_percent}%)")

print()

print(f"The species with the largest population is {largest_species} with {largest_count} penguins.")
print(f"The species with the smallest population is {smallest_species} with {smallest_count} penguins.")